name: replace
version: 1.0.3
description: An easy to use cross-platform regex replace command line util.
repository: https://github.com/robrbecker/replace

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  cli_script: ^0.2.3
  file: ^6.0.0
  glob: ^2.0.0

executables:
  replace:

cider:
  link_template:
    tag: https://github.com/robrbecker/replace/releases/tag/%tag%
    diff: https://github.com/robrbecker/replace/compare/%from%...%to%